---
- name: Install Packages
  ansible.builtin.dnf:
    name:
      - python
      - python-setuptools
      - gzip
      - unzip
      - tar
      - git

- name: Install docker
  ansible.builtin.dnf:
    name: "docker"

- name: Install Pip
  ansible.builtin.dnf:
    name: python-pip

- name: Docker config
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/docker
    line: 'OPTIONS="--log-driver=json-file --log-opt max-size=50m --log-opt max-file=1 --default-ulimit nofile=8192:65535 --bip=172.17.42.1/16 --mtu=9001"'
    regexp: '^OPTIONS'
    state: present

- name: Dangling volumes cron
  ansible.builtin.copy:
    src: docker-gc-dangling-volumes.sh
    dest: /etc/cron.hourly/
    mode: 0755

- name: Housekeeping
  ansible.builtin.copy:
    src: docker_housekeeping.sh
    dest: /usr/local/bin
    mode: 0755

- name: Python docker
  ansible.builtin.pip:
    name: docker
    extra_args: --ignore-installed
