---
- name: Install Packages
  package:
    name:
      - python
      - python-setuptools
      - gzip
      - unzip
      - tar
      - git

- name: Install Docker with amazon-linux-extras
  command: "amazon-linux-extras install docker"
  register: extrasinstall
  changed_when: "'already installed and latest version\nNothing to do' not in extrasinstall.stdout"

- name: Extract docker-20.10.5.tgz into /tmp for x86_64
  when: ansible_facts['architecture'] == "x86_64"
  unarchive:
    src: https://download.docker.com/linux/static/stable/x86_64/docker-20.10.5.tgz
    dest: /
    remote_src: yes

- name: Extract docker-20.10.5.tgz into /tmp for aarch64
  when: ansible_facts['architecture'] == "aarch64"
  unarchive:
    src: https://download.docker.com/linux/static/stable/aarch64/docker-20.10.5.tgz
    dest: /
    remote_src: yes

- name: Copy docker binary to /bin
  copy:
    src: /docker/docker
    dest: /bin/docker
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Update with latest packages
  yum:
    name: "*"

- name: Install Pip
  yum:
    name: python-pip

- name: docker config
  lineinfile:
    path: /etc/sysconfig/docker
    line: 'OPTIONS="--log-driver=json-file --log-opt max-size=50m --log-opt max-file=1 --default-ulimit nofile=4096:65535 --bip=172.17.42.1/16 --mtu=9001"'
    regexp: '^OPTIONS'
    state: present

- name: dangling volumes cron
  copy:
    src: docker-gc-dangling-volumes.sh
    dest: /etc/cron.hourly/
    mode: 0755

- name: housekeeping
  copy:
    src: docker_housekeeping.sh
    dest: /usr/local/bin
    mode: 0755

- name: python docker
  pip:
    name: docker
    extra_args: --ignore-installed

- name: ansible create directory example
  file:
    path: /home/jenkins/.docker/cli-plugins
    state: directory

- name: install buildx x86
  when: ansible_facts['architecture'] == "x86_64"
  get_url:
    url: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
    dest: /home/jenkins/.docker/cli-plugins/buildx
    mode: 0755

- name: install buildx arn
  when: ansible_facts['architecture'] == "x86_64"
  get_url:
    url: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-arm-v7
    dest: /home/jenkins/.docker/cli-plugins/buildx
    mode: 0755
