- name: docker
  yum:
    name: docker

- name: docker config
  lineinfile:
    path: /etc/sysconfig/docker
    line: 'OPTIONS="--log-driver=json-file --log-opt max-size=50m --log-opt max-file=1 --default-ulimit nofile=4096:65535 --bip=172.17.42.1/16 --mtu=9001"'
    regexp: '^OPTIONS'
    state: present

- name: Enable the docker service
  service:
    name: docker.service
    enabled: yes
    
- name: dangling volumes cron
  copy:
    src: docker-gc-dangling-volumes.sh
    dest: /etc/cron.hourly/
    mode: 0755

- name: python docker
  pip:
    name: docker
